client_id: janascard-qsource3-40e52cfa-8bce-4572-b4b2-c5bc7de43018
topic_base: "qsource3"
device_name: "QSource3"
mqtt_broker: "test.mosquitto.org"
mqtt_port: 1883
mqtt_connection_timeout: 60

r0: 5e-3
qsource3_com_port: "COM1"
status_interval: 1000
