client_id: janascard-qsource3-40e52cfa-8bce-4572-b4b2-c5bc7de43018
topic_base: "lqt/qsource3"
device_name: "QSource3"
mqtt_broker: "localhost"
mqtt_port: 1883
mqtt_connection_timeout: 60

number_of_ranges: 3
r0: 4e-3
qsource3_com_port: "ASRL/dev/ttyUSB0::INSTR"
status_interval: 1000

# Full path to settings file due to running as a service
settings_file: "/home/jasik/qsource3-mqtt/settings.json"
